### ISSUE TITLE
No such file or directory: 'ivector-plda-scoring'

### ISSUE THREAD

**Issue by TitaniumTTL** [FAKEBOB-adversarial-attack/FAKEBOB#17]
hello, I'm impressed with your work.
when I run build_spk_models.py, I face the error: No such file or directory: 'ivector-plda-scoring'
But   'ivector-plda-scoring' exists in KALDI_ROOT/src/ivectorbin.  

root@c9c5cf113b47:/mounted# python3 build_spk_models.py
----- step 1: generate ivector identity and corresponding speaker model -----
--- extracting and scoring ---
Traceback (most recent call last):
  File "build_spk_models.py", line 114, in <module>
    n_jobs=n_jobs, flag=1, debug=debug)
  File "/mounted/ivector_PLDA_kaldiHelper.py", line 332, in score_existing
    plda=plda, mean_vec=mean_vec, transform_mat=transform_mat, debug=debug)
  File "/mounted/ivector_PLDA_kaldiHelper.py", line 277, in plda_scoring
    p = subprocess.Popen(args) if debug else subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ivector-plda-scoring'

**Comment by TitaniumTTL** [comment]
I have successfully run scripts in docker environment
