### ISSUE TITLE
test.py:  No such file or directory: 'ivector-plda-scoring'

### ISSUE THREAD

**Issue by KujouAika** [FAKEBOB-adversarial-attack/FAKEBOB#9]
Excuse me. 
I met the problem in run test.py and not sure it from kaldi or code:

Traceback (most recent call last):
  File "test.py", line 94, in <module>
    decisions, _ = iv_csi_model.make_decisions(audio_list, debug=debug, n_jobs=n_jobs)

  File "/mnt/hgfs/share_for_ubuntu/FAKEBOB/ivector_PLDA_CSI.py", line 124, in make_decisions
    score_array = self.score(audios, fs=fs, bits_per_sample=bits_per_sample, n_jobs=n_jobs, debug=debug)

  File "/mnt/hgfs/share_for_ubuntu/FAKEBOB/ivector_PLDA_CSI.py", line 116, in score
    score_array = self.kaldi_helper.score(audio_list, self.utt_ids, n_jobs=n_jobs, flag=1, train_ivector_scp=self.train_ivector_scp, debug=debug)

  File "/mnt/hgfs/share_for_ubuntu/FAKEBOB/ivector_PLDA_kaldiHelper.py", line 359, in score
    self.plda_scoring(train_ivector_scp=train_ivector_scp, test_ivector_scp=test_ivector_scp, trials_file=trials_file, scores_file=scores_file, 

  File "/mnt/hgfs/share_for_ubuntu/FAKEBOB/ivector_PLDA_kaldiHelper.py", line 277, in plda_scoring
    p = subprocess.Popen(args) if debug else subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

  File "/home/neu/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/home/neu/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ivector-plda-scoring'

**Comment by GolferChen** [comment]
Seems like you didn't correctly compile **Kaldi**. **ivector-plda-scoring** is an executable file after **Kaldi** is compiled.
You can run `which ivector-plda-scoring` in your terminal to locate it. If nothing outputs, you may need to re-build **Kaldi**.

**Comment by GolferChen** [comment]
Normally, ivector-plda-scoring will be in `XXX/kaldi/src/ivectorbin`

**Comment by KujouAika** [comment]
I see :)
